name: Trigger auto deployment for next-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ ci-release ]
    paths:
    - '**'
    - '.github/workflows/next-container-AutoDeployTrigger-275e613d-7c01-4180-98d1-31d604262091.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: index.docker.io
          username: ${{ secrets.NEXTCONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.NEXTCONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: index.docker.io/bricks9711/blog-bricksite:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEXTCONTAINER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n next-container -g blog-bricksite --server index.docker.io --username  ${{ secrets.NEXTCONTAINER_REGISTRY_USERNAME }} --password ${{ secrets.NEXTCONTAINER_REGISTRY_PASSWORD }}
            az containerapp update -n next-container -g blog-bricksite --image index.docker.io/bricks9711/blog-bricksite:${{ github.sha }}
